services:
  sqlserver:
    build:
      context: ./BackEnd/
      dockerfile: Dockerfile.sqlserver
    container_name: BugTracker_Persistance
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    # ports:
    #   - "1556:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U ${SQL_USER} -P ${SA_PASSWORD} -Q 'SELECT 1' -C",
        ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 30s

  bugtrackerapi:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: BugTracker_API
    depends_on:
      sqlserver:
        condition: service_healthy
    # ports:
    #   - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    #   - ${HTTPS_SERVER_PORT}:${HTTPS_SERVER_PORT}
    environment:
      # ASPNETCORE_URLS: http://0.0.0.0:80;
      REACT_APP_PORT: 90
      DOMAIN_URL: ${DOMAIN_URL}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionString: Server=${SQL_SERVER_HOST};Database=${SQL_DATABASE};User ID=${SQL_USER};Password=${SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=true;

  bugtrackerui:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
      args:
        HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
        DOMAIN_URL: bugtrackerapi

    container_name: BugTracker_UI
    depends_on:
      - bugtrackerapi
    ports:
      - ${REACT_APP_PORT}:90
    # environment:
    #   DomainName: ${DOMAIN_URL}

volumes:
  sql_data:
