services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: BugTracker_Persistance
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1556:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck: # Add this healthcheck section
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U ${SQL_USER} -P ${SA_PASSWORD} -Q 'SELECT 1'",
        ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s

  bugtrackerapi:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: BugTracker_API
    depends_on:
      - sqlserver
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
      - ${HTTPS_SERVER_PORT}:${HTTPS_SERVER_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
      DOMAIN_URL: ${DOMAIN_URL}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      JwtSecretKey: ${JWT_SECRET_KEY}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionString: Server=${SQL_SERVER_HOST};Database=${SQL_DATABASE};User ID=${SQL_USER};Password=${SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=true;

  bugtrackerui:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: BugTracker_UI
    depends_on:
      - bugtrackerapi
    ports:
      - ${REACT_APP_PORT}:80
    environment:
      HttpServerPort: ${HTTP_SERVER_PORT}
      DomainName: ${DOMAIN_URL}

volumes:
  sql_data:
